### ISSUE TITLE
i'm having an issue with the cookie

### ISSUE THREAD

**Issue by lolbob** [kcwiki/chrome-extension-dmm#1]
since its kinda complicated can we talk this over discord?

i'm kinda lost on which HTTP headers you'll need too, i got 69 requests and the first one is the one with error/area/

i've tried everything suggested and cant get the cookie to work.

**Comment by dexhunter** [comment]
Any update on this issue?

**Comment by gakada** [comment]
What is the problem again? [dmm.js](https://github.com/gakada/DMM/blob/master/dmm.js) changes `ckcy=2` to `ckcy=1` and `cklg=ja` to `cklg=welcome` in the `Cookie` header for _all_ requests on `*://*.dmm.com/*`, that is all.

From what I've tried today, seems like:

* You have to use Japanese.
* Some games work without this extension.
* Some games only work with this extension.
* Some games use IP based detection (at least I can `curl` a request and get different results based on IP).
