### ISSUE TITLE
Connection reset

### ISSUE THREAD

**Issue by DAS58** [kcwiki/chrome-extension-dmm#3]
I've been using this extension for around a month or two, but in about the last several weeks, I can't open Kancolle unless I'm in certain time of the day. The screen says "the connection was reset" and several of the scripts fail.
[
![image](https://user-images.githubusercontent.com/21984412/89795489-aa594600-db52-11ea-89ab-5949e10fde4d.png)
](url)

**Comment by gakada** [comment]
It might be ok (or not ok) for some DMM/etc. scripts to fail (e.g., an ad blocker can block some of them, without any issues, while some local network problems might cause issues). This extension only deals with `203.104.209.7` (as far as blocking/redirecting goes), so you need to check those requests, anything else is probably local network problems.

**Comment by Biogs** [comment]
![Screenshot 2020-11-16 180047](https://user-images.githubusercontent.com/74573840/99322498-aca7fc00-2835-11eb-924f-f0fd7a95bf44.png)
I'm not sure what's wrong. I've downloaded from the ZIP, but there seems to be something missing. Gadget_HTML5 I think.
