### ISSUE TITLE
Failed to Load

### ISSUE THREAD

**Issue by Biogs** [kcwiki/chrome-extension-dmm#4]
![image](https://user-images.githubusercontent.com/74573840/99340613-f56baf00-284d-11eb-9ad3-1d16b768f7e6.png)
I'm not sure what's wrong. I've downloaded from the ZIP, but there seems to be something missing. Gadget_HTML5 I think. I also just started using this. 
Edit: I tried using the cache download and I'm still not sure

**Comment by gakada** [comment]
What is the full path that is 404ing?

Note: if you don't have a KC account already, it won't load (return 404). For a new account, you need a full Japanese VPN to register it, with this extension disabled, then, once there is an account, VPN can be disabled and this extension can be used.

**Comment by Biogs** [comment]
I'll try

**Comment by Biogs** [comment]
It still
![Screenshot 2020-11-18 074306](https://user-images.githubusercontent.com/74573840/99537887-d9612e00-2971-11eb-9617-0c54b31e916c.png)
 doesn't seem to work

**Comment by Biogs** [comment]
It says that the html is missing or something like that. If it helps I'm using SoftEther

**Comment by gakada** [comment]
So you don't have a KC account / starting a new game? As I said, this extension doesn't handle account creation, only logins with existing accounts. Attempting to create an account with this extension enabled _should_ result in a 404 screen from `https://kcwiki.github.io/cache/kcs2/world.html?osapi_root=osapi.dmm.com`, so you have to disable it during the account creation process and use just SoftEther/etc. (with Japanese location).

**Comment by Biogs** [comment]
I did

**Comment by gakada** [comment]
Well you can check the path in that error https://user-images.githubusercontent.com/74573840/99340613-f56baf00-284d-11eb-9ad3-1d16b768f7e6.png, if it is `world.html` then the game thinks it is a new account.

**Comment by Biogs** [comment]
I tried making different accounts on a japanese vpn but I still get the same message

**Comment by Biogs** [comment]
Weird thing is that other games work with the vpn

**Comment by Biogs** [comment]
I tried making an account over a japanese vpn and it stull didn't work so I'm not sure what's wrong

**Comment by gakada** [comment]
Maybe take this to discord ([wikia's](https://kancolle.fandom.com/wiki/KanColle_Wiki) or [reddit's](https://www.reddit.com/r/kancolle/)). Issues are for actual extension bugs, I don't think there is a bug.
