### ISSUE TITLE
No longer loading into the game

### ISSUE THREAD

**Issue by FirstDagger** [kcwiki/chrome-extension-dmm#5]
![chrome_2021-01-13_20-12-08](https://user-images.githubusercontent.com/8125998/104498174-a1761000-55db-11eb-8f30-051728f0bac7.png)

**Comment by gakada** [comment]
Still works for me. The extension (version 0.0.2) should be enabled (it will be 403 if it is disabled, or if access to the sites is disabled; 403 is what the original server is returning, e.g., on http://203.104.209.7/gadget_html5/js/kcs_const.js, if the extension is enabled with access to the sites, then it will 307 redirect such requests to the cache, e.g., https://kcwiki.github.io/cache/gadget_html5/js/kcs_const.js, which will give 200), like so:

![1610575331](https://user-images.githubusercontent.com/13043588/104515732-884e7d00-5636-11eb-8c97-94a1ba370c0b.png)
